"""empty message

Revision ID: 179bb88b866e
Revises: 1caf039d356b
Create Date: 2018-01-24 18:15:58.840063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179bb88b866e'
down_revision = '1caf039d356b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('email', sa.String(length=64), nullable=False))
    op.add_column('company', sa.Column('password', sa.String(length=256), nullable=False))
    op.create_index(op.f('ix_company_email'), 'company', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_email'), table_name='company')
    op.drop_column('company', 'password')
    op.drop_column('company', 'email')
    # ### end Alembic commands ###
