"""empty message

Revision ID: a5c1fedcc142
Revises: 179bb88b866e
Create Date: 2018-01-24 18:39:20.002148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5c1fedcc142'
down_revision = '179bb88b866e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'address',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('company', 'intro',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('company', 'website',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'website',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('company', 'intro',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('company', 'address',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
