"""empty message

Revision ID: ebdafa8379b6
Revises: 80f27fe2be7b
Create Date: 2018-01-17 10:21:29.124929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdafa8379b6'
down_revision = '80f27fe2be7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'status')
    # ### end Alembic commands ###
